# Basic Data Structures

# Lists (ordered collection of various objects)

### Instantiation

In [1]:
data = [1.7,"hello",4,"cat"]

### Accessing the first element

In [2]:
data[0]

1.7

### Updating an element

In [3]:
data[1] = 3.5
# data = [1.7,3.5,4,"cat"]
print(data)

[1.7, 3.5, 4, 'cat']


### Slicing a list (get the first 3 elements)

In [4]:
data[0:3]

[1.7, 3.5, 4]

### Finding the length of a list

We use the len() function.

In [5]:
len(data)

4

### Accessing elements at the end of a list

In [6]:
last = data[-1]
print(last)
#Should output "cat"

cat


### Traversing through a list

This is useful if you don't need the index and if you're not changing anything.

In [7]:
for item in data:
    print(item)

1.7
3.5
4
cat


### Traversing a list by indices in the list

This technique is useful if you want to change items in the list.

In [8]:
for i in range(len(data)):
    print(data[i])

1.7
3.5
4
cat


### Contains

This method will return either True or False.

In [9]:
6 in data
#Returns False

False

In [10]:
1.7 in data
#Returns True

True

### Removing an element from a list by the item's position

In [11]:
del data[1]
#Deletes 3.5 from the list
print(data)

[1.7, 4, 'cat']


### Remove a single element from a list by the item's value

In [12]:
data.remove('cat')
#Removes 'cat' from the list
print(data)

[1.7, 4]


### Split string into a list

We want to break a string into a list based on a delimiter, which is usually a space " ".

In [13]:
"my string is".split(" ")
# makes a list [“my”,”string”,”is”]

['my', 'string', 'is']

### Make string from a list or array of strings

In [14]:
" ".join( ["my","string","is"])

'my string is'

# Dictionary (collection of key-value pairs)

In Python, we call a collection of key-value pairs a dictionary, and a mix of key types is allowed.
### Instantiation

In [15]:
empty = {}

song = {"A" : "do", "B": "re", "C" : "mi"}
#"A"->"do"
#"B"->"re"
#"C"->"mi"

### Finding the size of the dictionary

We also use the len() function to find the size of the dictionary.

In [16]:
len(song)

3

### Looking up values by key in the dictionary

In [17]:
song['A']

'do'

### Updating/Setting a value

In [18]:
song['A'] = 'fa'
song['A']

'fa'

### Get the list of keys

We use the keys() function.

In [19]:
song.keys()
#Returns A,B,C

dict_keys(['A', 'B', 'C'])

### Get the list of values

We use the values() function.

In [20]:
song.values()
#Returns fa, re, mi

dict_values(['fa', 're', 'mi'])

### Determining if a key is present in the dictionary

In [21]:
'A' in song

True

In [22]:
'Z' in song

False

### Removal

In [23]:
del song['A']
print(song)

{'B': 're', 'C': 'mi'}


### Traversal through the dictionary, iterating by key

In [24]:
for key in song:
    print(song[key])

re
mi


# 2D Arrays

In Python, we use the NumPy package, which is used for scientific computing with Python.

In [25]:
import numpy as np

### Instantiation

In [26]:
data = np.array([[1,2],[3,4]])

### Checking the array type

In [27]:
data.dtype

#Array of Integers

dtype('int64')

### Finding the dimensions of an array

In [28]:
data.shape

#2 rows and 2 colums

(2, 2)

### Find the number of rows or columns in an array

In [29]:
#Number of rows
print("Rows:", data.shape[0])

#Number of columns
print("Columns:", data.shape[1])

Rows: 2
Columns: 2


### Accessing the first value in an array

In [30]:
data[0,0]
#Returns 1

np.int64(1)

### Setting a value

In [31]:
data[0,0] = 5

### Copying an array

We copy an array by using NumPy's copy function.

In [32]:
new_data = np.copy(data)
print(new_data)

[[5 2]
 [3 4]]


### Creating a 2x2 array of all zeroes

We create an array of all zeroes by using NumPy's zeros function.

In [33]:
data = np.zeros((2,2))
print(data)

[[0. 0.]
 [0. 0.]]


### Creating a 2x2 array of all ones

We create an array of all ones by using NumPy's ones function.

In [34]:
data = np.ones((2,2))
print(data)

[[1. 1.]
 [1. 1.]]


### Slicing an array

In this example, we are trying to get the first column of the array.

In [35]:
data = np.array([[1,2],[3,4]])

print(data[0:2,0])
#OR
print()
print(data[:,0])

[1 3]

[1 3]


### Copy one array into a part of an array

In this example, we want to set the first column to zeroes.

In [36]:
print(data)

data[:,0] = [0,0]
print()
print(data)

[[1 2]
 [3 4]]

[[0 2]
 [0 4]]


### Transpose (flipping rows and columns)

We transpose an array bu using the transpose() function.

In [37]:
print(data.transpose())

[[0 0]
 [2 4]]


### Combining two arrays vertically

To combine two arrays vertically, we use NumPy's vstack function.

In [38]:
row1 = np.array([1,2,3])
row2 = np.array([4,5,6])
np.vstack((row1,row2))

array([[1, 2, 3],
       [4, 5, 6]])

### Reshaping a 1D array to a 2D array

In [39]:
np.arange(1,7).reshape(3,2)
#Shape arrays row first

array([[1, 2],
       [3, 4],
       [5, 6]])

### Reshape a 2D array into a 1D array

To reshape a 2D array into a 1D array, we want to use the flatten function, which returns a copy of the array collapsed into a 1D array.

In [40]:
print(data.flatten())

[0 2 0 4]


# Helpful Links


1. https://sebastianraschka.com/blog/2014/matrix_cheatsheet_table.html
2. https://cheatsheets.quantecon.org/
3. http://hyperpolyglot.org/numerical-analysis
4. http://mathesaurus.sourceforge.net/matlab-python-xref.pdf
